### ISSUE TITLE
tests.test_eik_files.Tests.test_read_eik_from_gx fails in github actions

### ISSUE THREAD

**Issue by nmandell** [landreman/gx_geometry#2]
Not sure why this test is failing on the main branch when it was passing before and there haven't been any changes to main yet. The test passes on my local machine.

**Comment by landreman** [comment]
This issue seems to be related to updates to the netcdf4 package in mid-June, after the last successful gx_geometry CI run on Jun 5 and before the CI started failing today. Forcing the CI to use the previous version of netcdf4, the test works again: https://github.com/landreman/gx_geometry/actions/runs/10050069999/job/27777277014

**Comment by nmandell** [comment]
Fixed by a4d168b
